export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  VERIFY_OTP: '/verify-otp',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  ROLE_SELECTION: '/role-selection',
  DASHBOARD: '/dashboard',
  SEARCH: '/search',
  EXPERT_PROFILE: '/expert/:id',
  BOOKING: '/booking/:id',
  PAYMENT: '/payment',
  PAYMENT_SUCCESS: '/payment/success',
  PAYMENT_FAILURE: '/payment/failure',
  LIVE_SESSION: '/live-session/:id',
  MESSAGES: '/messages',
  LEARNING: '/learning',
  REVIEWS: '/reviews',
  NOTIFICATIONS: '/notifications',
  SETTINGS: '/settings',
  ADMIN: '/admin',
  ADMIN_USERS: '/admin/users',
  ADMIN_EXPERTS: '/admin/experts',
  ADMIN_TECHNOLOGIES: '/admin/technologies',
  ADMIN_BOOKINGS: '/admin/bookings',
  ADMIN_PAYMENTS: '/admin/payments',
  ADMIN_REVIEWS: '/admin/reviews',
  ADMIN_ANALYTICS: '/admin/analytics',
  ADMIN_REPORTS: '/admin/reports',
  NOT_FOUND: '*',
} as const;

export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    LOGOUT: '/auth/logout',
    VERIFY_OTP: '/auth/verify-otp',
    RESEND_OTP: '/auth/resend-otp',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
    REFRESH_TOKEN: '/auth/refresh-token',
    SOCIAL_LOGIN: '/auth/social-login',
  },
  USERS: {
    PROFILE: '/users/profile',
    UPDATE_PROFILE: '/users/profile',
    CHANGE_PASSWORD: '/users/change-password',
    UPLOAD_AVATAR: '/users/avatar',
    PREFERENCES: '/users/preferences',
    STATS: '/users/stats',
  },
  EXPERTS: {
    LIST: '/experts',
    DETAIL: (id: string) => `/experts/${id}`,
    SEARCH: '/experts/search',
    AVAILABILITY: (id: string) => `/experts/${id}/availability`,
    REVIEWS: (id: string) => `/experts/${id}/reviews`,
    TECHNOLOGIES: '/experts/technologies',
  },
  TECHNOLOGIES: {
    LIST: '/technologies',
    CATEGORIES: '/technologies/categories',
    TRENDING: '/technologies/trending',
    SEARCH: '/technologies/search',
  },
  BOOKINGS: {
    CREATE: '/bookings',
    LIST: '/bookings',
    DETAIL: (id: string) => `/bookings/${id}`,
    CANCEL: (id: string) => `/bookings/${id}/cancel`,
    VALIDATE_COUPON: '/bookings/validate-coupon',
  },
  PAYMENTS: {
    CREATE_ORDER: '/payments/create-order',
    VERIFY: '/payments/verify',
    TRANSACTIONS: '/payments/transactions',
    INVOICE: (id: string) => `/payments/${id}/invoice`,
  },
  CHAT: {
    CONVERSATIONS: '/chat/conversations',
    MESSAGES: (conversationId: string) => `/chat/conversations/${conversationId}/messages`,
    SEND: (conversationId: string) => `/chat/conversations/${conversationId}/send`,
    MARK_READ: (conversationId: string) => `/chat/conversations/${conversationId}/read`,
  },
  NOTIFICATIONS: {
    LIST: '/notifications',
    MARK_READ: (id: string) => `/notifications/${id}/read`,
    MARK_ALL_READ: '/notifications/read-all',
    PREFERENCES: '/notifications/preferences',
  },
  REVIEWS: {
    CREATE: '/reviews',
    LIST: '/reviews',
    DETAIL: (id: string) => `/reviews/${id}`,
    HELPFUL: (id: string) => `/reviews/${id}/helpful`,
  },
  LEARNING: {
    COURSES: '/learning/courses',
    CERTIFICATES: '/learning/certificates',
    ACHIEVEMENTS: '/learning/achievements',
    STATS: '/learning/stats',
    SESSIONS: '/learning/sessions',
  },
  ADMIN: {
    STATS: '/admin/stats',
    USERS: '/admin/users',
    EXPERTS: '/admin/experts',
    BOOKINGS: '/admin/bookings',
    PAYMENTS: '/admin/payments',
    TECHNOLOGIES: '/admin/technologies',
    REVIEWS: '/admin/reviews',
    ANALYTICS: '/admin/analytics',
    REPORTS: '/admin/reports',
  },
} as const;
